#!/usr/bin/env python

from mmpdblib import commandline
import signal

if __name__ == "__main__":
    signal.signal(signal.SIGINT, signal.SIG_DFL)  # Allow ^C to kill the process.
    signal.signal(signal.SIGPIPE, signal.SIG_DFL) # Allow the output pipe to be closed
    commandline.main()
